# Site Settings
title: 丁曙光的博客
email: dingshuguang1@gmail.com
description: 分享 思考 兴趣
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dingshuguang.ml" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Jekflix
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
#github_username: github_username
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - 丁曙光
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 首页
    url: /
  - title: 关于
    url: /about/
  - title: 链接
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
