title: dingshuguang # your site title
author: dingshuguang
email: dingshuguang1@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write and Think
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dingshuguang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:   # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer
social:
  name: dingshuguang
  links:
    #- https://www.facebook.com/ben.balter
    #- https://www.linkedin.com/in/BenBalter
    #- https://plus.google.com/+BenBalter
    #- https://github.com/benbalter
    #- https://keybase.io/benbalter

disqus:
  shortname: dingshuguang # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: author
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
