permalink: /:categories/:title/
url: "https://dingshuguang.ml"
full_name: "Saigon Jekyll Theme"
first_name: "dingshuguang's blog"
last_name: ""
blog_title: "Title"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2020"
google_analytics_code: ""
aboutme: "think write "
