logo_title: 記憶碎片

style: black

favicon: /favicon.ico

menu:
#  文章: /project
#  域名: /domain
#  友联: /links
  关于: /about
#  Github: https://github.com/

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: IbbfT8u0h3OfsOuz912KHBPH-gzGzoHsz
  appKey: zjgOj218GRnxCb4wt4Uy8wIs

highlight:
  enable: true

love: false
click_show_text: true

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 4
  wpm: 200